name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    name: Prettier Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          npm ci --prefer-offline --no-audit --no-optional
          cd functions
          npm ci --prefer-offline --no-audit --no-optional

      - name: Run Prettier Tests
        run: npm run prettier

  eslint:
    name: ESLint Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          npm ci --prefer-offline --no-audit --no-optional
          cd functions
          npm ci --prefer-offline --no-audit --no-optional

      - name: Run ESLint Tests
        run: npm run eslint

  jest:
    name: React Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          npm ci --prefer-offline --no-audit --no-optional
          cd functions
          npm ci --prefer-offline --no-audit --no-optional

      - name: Run react-scripts Tests
        run: npm run test
        env:
          REACT_APP_FIREBASE_API_KEY: AIzaSyDcJMYRqjq9HVPN5651DUQJ5LtudV4VOro
          REACT_APP_FIREBASE_AUTH_DOMAIN: basis-scottsdale-library.firebaseapp.com
          REACT_APP_FIREBASE_DATABASE_URL: https://basis-scottsdale-library.firebaseio.com
          REACT_APP_FIREBASE_PROJECT_ID: basis-scottsdale-library
          REACT_APP_FIREBASE_STORAGE_BUCKET: basis-scottsdale-library.appspot.com
          REACT_APP_FIREBASE_APP_ID: 1:547349848920:web:05b2531ebd920c8716bb2d
